### ISSUE TITLE
Support for CLI v5.2

### ISSUE THREAD

**Issue by mjarosch** [Sitecore-Hackathon/2022-Sitecore-Warriors#2]
This extension doesn't work with newer Sitecore CLI versions.

**Comment by mjarosch** [comment]
@nehemiahj Thanks for accepting my PR. Any chance the updated plugin will make its way up to nuget.org?

**Comment by nehemiahj** [comment]
I will update the plugin and confirm you.

**Comment by nehemiahj** [comment]
Nuget package has been published.

**Comment by mjarosch** [comment]
@nehemiahj Hello. I installed the plugin, but it is packaged with the older 'Sitecore.DevEx.Serialization.Client.dll', but Sitecore has moved the client to 'Sitecore.DevEx.Core.Client.dll' and 'Sitecore.DevEx.Core.Client.GraphQL.dll'.

**Comment by nehemiahj** [comment]
Let me check it today.

**Comment by nehemiahj** [comment]
I am testing it and publishing the plugin later today.

**Comment by mjarosch** [comment]
@nehemiahj Thank you so much! Let me know if there is anything I can do to help.

**Comment by nehemiahj** [comment]
Plugin package is ready and requested nuget.org to remove the current 5.x version so that I can push it. ETA: 1 - 2 days.

**Comment by nehemiahj** [comment]
I have published the package. v5.2.110. It will take few hours to propagate to the nuget.org search listing. 
https://www.nuget.org/packages/SitecoreWarriors.DevEx.Extensibility.Jobs/5.2.110

Note: There will be another update once Sitecore officially releases all the dependent packages for v5.2.113

**Comment by nehemiahj** [comment]
In your sitecore.json, please update the version for Jobs plugin to 5.2.110.

"SitecoreWarriors.DevEx.Extensibility.Jobs@5.2.110"
